  - name: install remi repo from rpm
    ansible.builtin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
  - name: install module enable redis remi 6.2
    ansible.builtin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
  - name: install install redis
    ansible.builtin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
  - name: replace address from 127.0.0.1 to 0.0.0.0
    replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
  - name: replace address from 127.0.0.1 to 0.0.0.0
    replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
  - name: enabel and start redis
    ansible.builtin.service:
      name: redis
      enabled: yes
      state: started