- name: replace mongo.repo file
  ansible.builtin.copy:
    src:  roles/common/templates/mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: install mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: present
- name: mongodb service enable
  ansible.builtin.service:
    name: mongod
    enabled: yes
    state: started
- name: mongo.conf replace value 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: mongodb service restart
  ansible.builtin.service:
    name: mongod
    state: restarted
   


