- name: stop the service {{component}}
  tags:
  - deployment
  ansible.builtin.systemd_service:
    name: "{{component}}"
    state: stopped
- name: remove /app data
  tags:
  - deployment
  ansible.builtin.file:
    path: /app
    state: absent
  


