- name: nginx installation
  ansible.builtin.package:
    name: nginx
    state: present
- name: remove content from html
  ansible.builtin.file:
     path: /usr/share/nginx/html/*
     state: absent

