- name: nodejs disable module and enable nodejs:18 modulue
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
- name: install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

