- name: import task nodejs.yml
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yml
- name: component app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yml
- name: Install packages based on package.json
  npm:
    path: /app
- name: cart systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yml
