- name: import task nodejs.yml
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yml
- name: cart app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yml
- name: cart systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yml
